// GENERATED by shruggie-brandbuilder. Keep this file in nextjs/ and the
// bundled font tree in fonts/ so every path remains local and deterministic.
import localFont from "next/font/local"

export const displayFont = localFont({
  src: [
    { path: "../fonts/woff2/SpaceGrotesk-Medium.woff2", weight: "500", style: "normal" },
    { path: "../fonts/woff2/SpaceGrotesk-Bold.woff2", weight: "700", style: "normal" },
  ],
  variable: "--font-display-role",
  display: "swap",
})

export const bodyFont = localFont({
  src: [
    { path: "../fonts/woff2/Geist-Regular.woff2", weight: "400", style: "normal" },
    { path: "../fonts/woff2/Geist-Medium.woff2", weight: "500", style: "normal" },
  ],
  variable: "--font-body",
  display: "swap",
})

export const monoFont = localFont({
  src: [
    { path: "../fonts/woff2/GeistMono-Regular.woff2", weight: "400", style: "normal" },
  ],
  variable: "--font-mono-role",
  display: "swap",
})

// Approved weights: Space Grotesk 500/700; Geist 400/500; Geist Mono 400
export const fontVariables = [
  displayFont.variable,
  bodyFont.variable,
  monoFont.variable,
].join(" ")
