// GENERATED by shruggie-brandbuilder.
export function OpenGraphImage({ className }: { className?: string }) {
  return (
    <img
      className={className}
      src="/insonic-social-preview-1280.png"
      alt="insonic, Voice archives, speaker models, and connected knowledge"
    />
  )
}
