// GENERATED by shruggie-brandbuilder.
"use client"

import { ThemeProvider } from "next-themes"
import type { ReactNode } from "react"

// Dark-first. Light exists as a reading-mode alternative for docs and blog.
// shadcn's :root/.dark convention is preserved so third-party blocks work;
// the default lives here instead.
export function Providers({ children }: { children: ReactNode }) {
  return (
    <ThemeProvider
      attribute="class"
      defaultTheme="dark"
      enableSystem={false}
      disableTransitionOnChange
    >
      {children}
    </ThemeProvider>
  )
}
