// SPDX-License-Identifier: Apache-2.0
package catalog

// Exact accepted schema3 DDL, frozen before current record reflection changes.
var historicalV3DDL = []string{
	"CREATE TABLE IF NOT EXISTS workspace (id TEXT PRIMARY KEY, revision BIGINT NOT NULL CHECK (revision>=0), schema_version BIGINT NOT NULL)",
	"CREATE TABLE IF NOT EXISTS operation_receipt (workspace_id TEXT NOT NULL, id TEXT NOT NULL, digest TEXT NOT NULL, revision BIGINT NOT NULL CHECK (revision>0), result TEXT NOT NULL, PRIMARY KEY(workspace_id,id), UNIQUE(workspace_id,revision), FOREIGN KEY(workspace_id) REFERENCES workspace(id))",
	"CREATE TABLE IF NOT EXISTS setting_revision (workspace_id TEXT NOT NULL, name TEXT NOT NULL, revision BIGINT NOT NULL CHECK (revision>0), value TEXT NOT NULL, PRIMARY KEY(workspace_id,name,revision), FOREIGN KEY(workspace_id) REFERENCES workspace(id))",
	"CREATE TABLE IF NOT EXISTS job (workspace_id TEXT NOT NULL, id TEXT NOT NULL, operation_id TEXT NOT NULL, duration_ms BIGINT NOT NULL CHECK(duration_ms BETWEEN 1 AND 60000), generation BIGINT NOT NULL CHECK(generation>0), state TEXT NOT NULL CHECK(state IN ('running','succeeded','failed','cancelled','interrupted')), PRIMARY KEY(workspace_id,id), UNIQUE(workspace_id,operation_id), FOREIGN KEY(workspace_id) REFERENCES workspace(id))",
	"CREATE TABLE IF NOT EXISTS job_attempt (workspace_id TEXT NOT NULL, id TEXT NOT NULL, job_id TEXT NOT NULL, owner_id TEXT NOT NULL, generation BIGINT NOT NULL CHECK(generation>0), state TEXT NOT NULL CHECK(state IN ('running','succeeded','failed','cancelled','interrupted')), lease_until BIGINT NOT NULL, started_ns BIGINT NOT NULL, ended_ns BIGINT, reason TEXT NOT NULL, PRIMARY KEY(workspace_id,id), UNIQUE(workspace_id,job_id,generation), FOREIGN KEY(workspace_id,job_id) REFERENCES job(workspace_id,id))",
	"CREATE TABLE IF NOT EXISTS workspace_lease (workspace_id TEXT NOT NULL, role TEXT NOT NULL, owner_id TEXT NOT NULL, generation BIGINT NOT NULL CHECK(generation>0), lease_until BIGINT NOT NULL, PRIMARY KEY(workspace_id,role), FOREIGN KEY(workspace_id) REFERENCES workspace(id))",
	"CREATE TABLE IF NOT EXISTS graph_target (workspace_id TEXT NOT NULL, id TEXT NOT NULL, next_sequence BIGINT NOT NULL CHECK(next_sequence>=0), checkpoint BIGINT NOT NULL CHECK(checkpoint>=0), owner_id TEXT, generation BIGINT NOT NULL CHECK(generation>=0), lease_until BIGINT NOT NULL, PRIMARY KEY(workspace_id,id), FOREIGN KEY(workspace_id) REFERENCES workspace(id))",
	"CREATE TABLE IF NOT EXISTS graph_event (workspace_id TEXT NOT NULL, target_id TEXT NOT NULL, sequence BIGINT NOT NULL CHECK(sequence>0), predecessor BIGINT NOT NULL CHECK(predecessor>=0), revision BIGINT NOT NULL CHECK(revision>0), operation_id TEXT NOT NULL, document TEXT NOT NULL, digest TEXT NOT NULL, PRIMARY KEY(workspace_id,target_id,sequence), FOREIGN KEY(workspace_id,target_id) REFERENCES graph_target(workspace_id,id), FOREIGN KEY(workspace_id,operation_id) REFERENCES operation_receipt(workspace_id,id))",
	"CREATE TABLE IF NOT EXISTS profile_revision (workspace_id TEXT NOT NULL,expected_backend_version TEXT,id TEXT NOT NULL,revision BIGINT NOT NULL,role TEXT NOT NULL,adapter TEXT NOT NULL,version TEXT NOT NULL,configuration TEXT NOT NULL,credential_id TEXT,PRIMARY KEY (workspace_id,id,revision),FOREIGN KEY (workspace_id) REFERENCES workspace(id),CHECK (revision>0), CHECK (role IN ('storage','catalog','graph')))",
	"CREATE TABLE IF NOT EXISTS artifact (workspace_id TEXT NOT NULL,id TEXT NOT NULL,digest TEXT NOT NULL,size BIGINT NOT NULL,kind TEXT NOT NULL,PRIMARY KEY (workspace_id,id),FOREIGN KEY (workspace_id) REFERENCES workspace(id),CHECK (size>=0 AND length(digest)=64))",
	"CREATE TABLE IF NOT EXISTS artifact_location (workspace_id TEXT NOT NULL,id TEXT NOT NULL,artifact_id TEXT NOT NULL,profile_id TEXT NOT NULL,profile_revision BIGINT NOT NULL,key TEXT NOT NULL,version TEXT,state TEXT NOT NULL,PRIMARY KEY (workspace_id,id),FOREIGN KEY (workspace_id) REFERENCES workspace(id),FOREIGN KEY (workspace_id,artifact_id) REFERENCES artifact(workspace_id,id),FOREIGN KEY (workspace_id,profile_id,profile_revision) REFERENCES profile_revision(workspace_id,id,revision),CHECK (profile_revision>0), CHECK (state IN ('available','missing','retired','pending')))",
	"CREATE TABLE IF NOT EXISTS media_entry (workspace_id TEXT NOT NULL,id TEXT NOT NULL,title TEXT NOT NULL,class TEXT NOT NULL,PRIMARY KEY (workspace_id,id),FOREIGN KEY (workspace_id) REFERENCES workspace(id))",
	"CREATE TABLE IF NOT EXISTS media_asset (workspace_id TEXT NOT NULL,id TEXT NOT NULL,artifact_id TEXT NOT NULL,role TEXT NOT NULL,duration_us BIGINT NOT NULL,PRIMARY KEY (workspace_id,id),FOREIGN KEY (workspace_id) REFERENCES workspace(id),FOREIGN KEY (workspace_id,artifact_id) REFERENCES artifact(workspace_id,id),CHECK (duration_us>=0))",
	"CREATE TABLE IF NOT EXISTS media_entry_asset (workspace_id TEXT NOT NULL,id TEXT NOT NULL,media_id TEXT NOT NULL,asset_id TEXT NOT NULL,role TEXT NOT NULL,PRIMARY KEY (workspace_id,id),FOREIGN KEY (workspace_id) REFERENCES workspace(id),FOREIGN KEY (workspace_id,media_id) REFERENCES media_entry(workspace_id,id),FOREIGN KEY (workspace_id,asset_id) REFERENCES media_asset(workspace_id,id))",
	"CREATE TABLE IF NOT EXISTS metadata_snapshot (workspace_id TEXT NOT NULL,id TEXT NOT NULL,asset_id TEXT NOT NULL,report_artifact_id TEXT,state TEXT NOT NULL,extractor TEXT NOT NULL,version TEXT NOT NULL,captured_iso TEXT NOT NULL,captured_unix_ns BIGINT NOT NULL,PRIMARY KEY (workspace_id,id),FOREIGN KEY (workspace_id) REFERENCES workspace(id),FOREIGN KEY (workspace_id,asset_id) REFERENCES media_asset(workspace_id,id),FOREIGN KEY (workspace_id,report_artifact_id) REFERENCES artifact(workspace_id,id),CHECK (state IN ('captured','no-embedded-metadata','partial','unsupported','failed')))",
	"CREATE TABLE IF NOT EXISTS metadata_observation (workspace_id TEXT NOT NULL,id TEXT NOT NULL,snapshot_id TEXT NOT NULL,family TEXT NOT NULL,tag TEXT NOT NULL,instance BIGINT NOT NULL,raw TEXT NOT NULL,value TEXT NOT NULL,unit TEXT,precision TEXT,PRIMARY KEY (workspace_id,id),FOREIGN KEY (workspace_id) REFERENCES workspace(id),FOREIGN KEY (workspace_id,snapshot_id) REFERENCES metadata_snapshot(workspace_id,id),CHECK (instance>=0))",
	"CREATE TABLE IF NOT EXISTS date_observation (workspace_id TEXT NOT NULL,id TEXT NOT NULL,media_id TEXT NOT NULL,observation_id TEXT,basis TEXT NOT NULL,literal TEXT NOT NULL,zone TEXT,offset_seconds BIGINT,rules_version TEXT,precision TEXT NOT NULL,resolved_iso TEXT,resolved_unix_ns BIGINT,PRIMARY KEY (workspace_id,id),FOREIGN KEY (workspace_id) REFERENCES workspace(id),FOREIGN KEY (workspace_id,media_id) REFERENCES media_entry(workspace_id,id),FOREIGN KEY (workspace_id,observation_id) REFERENCES metadata_observation(workspace_id,id))",
	"CREATE TABLE IF NOT EXISTS date_selection (workspace_id TEXT NOT NULL,id TEXT NOT NULL,media_id TEXT NOT NULL,revision BIGINT NOT NULL,date_id TEXT,policy TEXT NOT NULL,reason TEXT NOT NULL,PRIMARY KEY (workspace_id,id),FOREIGN KEY (workspace_id) REFERENCES workspace(id),FOREIGN KEY (workspace_id,media_id) REFERENCES media_entry(workspace_id,id),FOREIGN KEY (workspace_id,date_id) REFERENCES date_observation(workspace_id,id),CHECK (revision>0), UNIQUE (workspace_id,media_id,revision))",
	"CREATE TABLE IF NOT EXISTS speaker (workspace_id TEXT NOT NULL,id TEXT NOT NULL,name TEXT NOT NULL,PRIMARY KEY (workspace_id,id),FOREIGN KEY (workspace_id) REFERENCES workspace(id))",
	"CREATE TABLE IF NOT EXISTS speaker_segment (workspace_id TEXT NOT NULL,id TEXT NOT NULL,revision BIGINT NOT NULL,asset_id TEXT NOT NULL,speaker_id TEXT,start_us BIGINT NOT NULL,end_us BIGINT NOT NULL,channel BIGINT NOT NULL,attribution TEXT NOT NULL,clip_artifact_id TEXT,PRIMARY KEY (workspace_id,id,revision),FOREIGN KEY (workspace_id) REFERENCES workspace(id),FOREIGN KEY (workspace_id,asset_id) REFERENCES media_asset(workspace_id,id),FOREIGN KEY (workspace_id,speaker_id) REFERENCES speaker(workspace_id,id),FOREIGN KEY (workspace_id,clip_artifact_id) REFERENCES artifact(workspace_id,id),CHECK (revision>0 AND start_us>=0 AND end_us>start_us AND channel>=0))",
	"CREATE TABLE IF NOT EXISTS training_dataset (workspace_id TEXT NOT NULL,id TEXT NOT NULL,speaker_id TEXT NOT NULL,manifest_artifact_id TEXT NOT NULL,options TEXT NOT NULL,PRIMARY KEY (workspace_id,id),FOREIGN KEY (workspace_id) REFERENCES workspace(id),FOREIGN KEY (workspace_id,speaker_id) REFERENCES speaker(workspace_id,id),FOREIGN KEY (workspace_id,manifest_artifact_id) REFERENCES artifact(workspace_id,id))",
	"CREATE TABLE IF NOT EXISTS dataset_member (workspace_id TEXT NOT NULL,id TEXT NOT NULL,dataset_id TEXT NOT NULL,ordinal BIGINT NOT NULL,segment_id TEXT NOT NULL,segment_revision BIGINT NOT NULL,PRIMARY KEY (workspace_id,id),FOREIGN KEY (workspace_id) REFERENCES workspace(id),FOREIGN KEY (workspace_id,dataset_id) REFERENCES training_dataset(workspace_id,id),FOREIGN KEY (workspace_id,segment_id,segment_revision) REFERENCES speaker_segment(workspace_id,id,revision),CHECK (ordinal>=0 AND segment_revision>0), UNIQUE (workspace_id,dataset_id,ordinal))",
	"CREATE TABLE IF NOT EXISTS training_run (workspace_id TEXT NOT NULL,id TEXT NOT NULL,dataset_id TEXT NOT NULL,speaker_id TEXT NOT NULL,job_id TEXT NOT NULL,preparation_artifact_id TEXT NOT NULL,adapter TEXT NOT NULL,options TEXT NOT NULL,PRIMARY KEY (workspace_id,id),FOREIGN KEY (workspace_id) REFERENCES workspace(id),FOREIGN KEY (workspace_id,dataset_id) REFERENCES training_dataset(workspace_id,id),FOREIGN KEY (workspace_id,speaker_id) REFERENCES speaker(workspace_id,id),FOREIGN KEY (workspace_id,job_id) REFERENCES job(workspace_id,id),FOREIGN KEY (workspace_id,preparation_artifact_id) REFERENCES artifact(workspace_id,id))",
	"CREATE TABLE IF NOT EXISTS speaker_model (workspace_id TEXT NOT NULL,id TEXT NOT NULL,speaker_id TEXT NOT NULL,name TEXT NOT NULL,PRIMARY KEY (workspace_id,id),FOREIGN KEY (workspace_id) REFERENCES workspace(id),FOREIGN KEY (workspace_id,speaker_id) REFERENCES speaker(workspace_id,id))",
	"CREATE TABLE IF NOT EXISTS model_version (workspace_id TEXT NOT NULL,id TEXT NOT NULL,model_id TEXT NOT NULL,run_id TEXT NOT NULL,dataset_id TEXT NOT NULL,manifest_artifact_id TEXT NOT NULL,kind TEXT NOT NULL,PRIMARY KEY (workspace_id,id),FOREIGN KEY (workspace_id) REFERENCES workspace(id),FOREIGN KEY (workspace_id,model_id) REFERENCES speaker_model(workspace_id,id),FOREIGN KEY (workspace_id,run_id) REFERENCES training_run(workspace_id,id),FOREIGN KEY (workspace_id,dataset_id) REFERENCES training_dataset(workspace_id,id),FOREIGN KEY (workspace_id,manifest_artifact_id) REFERENCES artifact(workspace_id,id))",
	"CREATE TABLE IF NOT EXISTS model_artifact (workspace_id TEXT NOT NULL,id TEXT NOT NULL,version_id TEXT NOT NULL,artifact_id TEXT NOT NULL,role TEXT NOT NULL,format TEXT NOT NULL,PRIMARY KEY (workspace_id,id),FOREIGN KEY (workspace_id) REFERENCES workspace(id),FOREIGN KEY (workspace_id,version_id) REFERENCES model_version(workspace_id,id),FOREIGN KEY (workspace_id,artifact_id) REFERENCES artifact(workspace_id,id))",
	"CREATE TABLE IF NOT EXISTS model_association (workspace_id TEXT NOT NULL,id TEXT NOT NULL,model_id TEXT NOT NULL,speaker_id TEXT NOT NULL,revision BIGINT NOT NULL,reason TEXT NOT NULL,PRIMARY KEY (workspace_id,id),FOREIGN KEY (workspace_id) REFERENCES workspace(id),FOREIGN KEY (workspace_id,model_id) REFERENCES speaker_model(workspace_id,id),FOREIGN KEY (workspace_id,speaker_id) REFERENCES speaker(workspace_id,id),CHECK (revision>0), UNIQUE (workspace_id,model_id,speaker_id,revision))",
	"CREATE TABLE IF NOT EXISTS library_entry (workspace_id TEXT NOT NULL,id TEXT NOT NULL,asset_id TEXT NOT NULL,title TEXT NOT NULL,class TEXT NOT NULL,mode TEXT NOT NULL,source_locator TEXT NOT NULL,digest TEXT NOT NULL,size BIGINT NOT NULL,original_publication_id TEXT,subtitle_publication_id TEXT,duration_us BIGINT,facts TEXT NOT NULL,metadata TEXT NOT NULL,dates TEXT NOT NULL,report_publication_ids TEXT NOT NULL,revision BIGINT NOT NULL,PRIMARY KEY (workspace_id,id),FOREIGN KEY (workspace_id) REFERENCES workspace(id),FOREIGN KEY (workspace_id,id) REFERENCES media_entry(workspace_id,id),FOREIGN KEY (workspace_id,asset_id) REFERENCES media_asset(workspace_id,id),CHECK (revision>0 AND size>=0), CHECK (duration_us IS NULL OR duration_us>=0), CHECK (mode IN ('copy','reference')))",
	"CREATE TABLE IF NOT EXISTS base_model_install (workspace_id TEXT NOT NULL,id TEXT NOT NULL,name TEXT NOT NULL,version TEXT NOT NULL,digest TEXT NOT NULL,manifest TEXT NOT NULL,publication_ids TEXT NOT NULL,state TEXT NOT NULL,revision BIGINT NOT NULL,PRIMARY KEY (workspace_id,id),FOREIGN KEY (workspace_id) REFERENCES workspace(id),CHECK (revision>0), CHECK (state IN ('registered','available')))",
	"CREATE TABLE IF NOT EXISTS work_operation (workspace_id TEXT NOT NULL,journal_receipt_id TEXT NOT NULL,id TEXT NOT NULL,kind TEXT NOT NULL,payload TEXT NOT NULL,state TEXT NOT NULL,owner TEXT NOT NULL,generation BIGINT NOT NULL,lease_until BIGINT NOT NULL,phase TEXT NOT NULL,result TEXT NOT NULL,error TEXT NOT NULL,PRIMARY KEY (workspace_id,id),FOREIGN KEY (workspace_id) REFERENCES workspace(id),CHECK (generation>=0), CHECK (state IN ('pending','running','succeeded','failed','cancelled','interrupted')))",
	"CREATE TABLE IF NOT EXISTS library_cleanup (workspace_id TEXT NOT NULL,revision BIGINT NOT NULL,id TEXT NOT NULL,entry_id TEXT NOT NULL,state TEXT NOT NULL,PRIMARY KEY (workspace_id,id),FOREIGN KEY (workspace_id) REFERENCES workspace(id),CHECK (state IN ('pending','done')))",
	"CREATE TABLE IF NOT EXISTS artifact_publication (workspace_id TEXT NOT NULL, id TEXT NOT NULL, artifact_id TEXT NOT NULL, data TEXT NOT NULL, PRIMARY KEY(workspace_id,id), FOREIGN KEY(workspace_id) REFERENCES workspace(id))",
	"CREATE INDEX IF NOT EXISTS artifact_publication_content ON artifact_publication(workspace_id,artifact_id)",
}

const historicalV3ExpectedDigest = "a8199dcd916d4d210780fcdaf375c9bc626487c580116b2e496d4afbc89899d4"
