// GENERATED by BrandBuilder gen_egui.py. Idiomatic immediate-mode helpers.
use crate::{CapabilityError, Density, PointerPrecision, RuntimeCapabilities, ThemeMode};
use crate::tokens::Tokens;

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum ButtonIntent { Primary, Secondary, Ghost, Destructive }

fn fine_pointer_control_height(tokens: &Tokens, density: Density) -> f32 {
    (tokens.target_minimum - 2.0 * 8.0f32).max(1.0) * density.multiplier()
}

fn requires_conservative_target(pointer_precision: PointerPrecision, touch: bool) -> bool {
    touch || !matches!(pointer_precision, PointerPrecision::Fine)
}

fn install_style(ctx: &egui::Context, egui_theme: egui::Theme, theme: ThemeMode, density: Density, text_scale: f32, conservative_target: bool) {
    let tokens = Tokens::for_theme(theme, density);
    let mut style = egui_theme.default_style();
    for font in style.text_styles.values_mut() { font.size *= text_scale; }
    style.spacing.item_spacing = egui::vec2(tokens.spacing_control * (2.0 / 3.0), tokens.spacing_control / 6.0);
    style.spacing.button_padding = egui::vec2(tokens.spacing_control * (2.0 / 3.0), tokens.spacing_control / 3.0);
    let body_height = style.text_styles.get(&egui::TextStyle::Body).map(|font| font.size).unwrap_or(14.0);
    let profile_height = if conservative_target { tokens.target_minimum } else { fine_pointer_control_height(&tokens, density) };
    let control_height = profile_height.max(body_height + 2.0 * style.spacing.button_padding.y);
    style.spacing.interact_size = egui::vec2(control_height, control_height);
    style.visuals = egui_theme.default_visuals();
    style.visuals.panel_fill = tokens.background;
    style.visuals.override_text_color = Some(tokens.text_primary);
    style.visuals.widgets.noninteractive.fg_stroke.color = tokens.text_muted;
    style.visuals.widgets.inactive.fg_stroke.color = tokens.text_primary;
    style.visuals.widgets.hovered.fg_stroke.color = tokens.text_primary;
    style.visuals.widgets.active.fg_stroke.color = tokens.text_primary;
    style.visuals.selection.bg_fill = tokens.action;
    style.visuals.selection.stroke = egui::Stroke::new(tokens.focus_width, tokens.focus);
    ctx.set_style_of(egui_theme, style);
}

fn apply_scaled_style(ctx: &egui::Context, theme: ThemeMode, density: Density, text_scale: f32, conservative_target: bool) {
    match theme {
        ThemeMode::Light => install_style(ctx, egui::Theme::Light, ThemeMode::Light, density, text_scale, conservative_target),
        ThemeMode::Dark => install_style(ctx, egui::Theme::Dark, ThemeMode::Dark, density, text_scale, conservative_target),
        ThemeMode::System => {
            install_style(ctx, egui::Theme::Light, ThemeMode::Light, density, text_scale, conservative_target);
            install_style(ctx, egui::Theme::Dark, ThemeMode::Dark, density, text_scale, conservative_target);
        }
    }
    let preference = match theme {
        ThemeMode::Light => egui::ThemePreference::Light,
        ThemeMode::Dark => egui::ThemePreference::Dark,
        ThemeMode::System => egui::ThemePreference::System,
    };
    ctx.set_theme(preference);
}

pub fn apply_style(ctx: &egui::Context, theme: ThemeMode, density: Density) {
    apply_scaled_style(ctx, theme, density, 1.0, false);
}

pub fn apply_capabilities(ctx: &egui::Context, capabilities: &RuntimeCapabilities) -> Result<(), CapabilityError> {
    capabilities.validate()?;
    let conservative_target = requires_conservative_target(capabilities.pointer_precision, capabilities.touch);
    apply_scaled_style(ctx, capabilities.theme, capabilities.density, capabilities.text_scale, conservative_target);
    Ok(())
}

pub fn app_frame<R>(ui: &mut egui::Ui, capabilities: &RuntimeCapabilities, add_contents: impl FnOnce(&mut egui::Ui) -> R) -> Result<egui::InnerResponse<R>, CapabilityError> {
    apply_capabilities(ui.ctx(), capabilities)?;
    Ok(egui::CentralPanel::default().show(ui, add_contents))
}

pub fn button(ui: &mut egui::Ui, label: impl Into<egui::WidgetText>, intent: ButtonIntent, disabled: bool) -> egui::Response {
    let tokens = Tokens::for_theme(if ui.visuals().dark_mode { ThemeMode::Dark } else { ThemeMode::Light }, Density::Comfortable);
    let (fill, text) = match intent {
        ButtonIntent::Primary => (tokens.action, tokens.on_action),
        ButtonIntent::Secondary => (tokens.card, tokens.text_primary),
        ButtonIntent::Ghost => (egui::Color32::TRANSPARENT, tokens.text_primary),
        ButtonIntent::Destructive => (tokens.destructive, tokens.on_destructive),
    };
    let (fill, text) = if disabled { (tokens.card, tokens.text_muted) } else { (fill, text) };
    let label = egui::WidgetText::color(label.into(), text);
    let control = egui::Button::new(label).fill(fill).stroke(egui::Stroke::new(1.0, text)).min_size(ui.spacing().interact_size);
    if disabled {
        ui.scope(|ui| {
            // egui::Ui::disable multiplies painter opacity; keep disabled semantics without fading readable text.
            ui.style_mut().visuals.disabled_alpha = 1.0;
            ui.add_enabled(false, control)
        }).inner
    } else {
        ui.add(control)
    }
}

pub fn icon_button(ui: &mut egui::Ui, accessible_label: &str, glyph: &str, disabled: bool) -> egui::Response {
    let response = ui.add_enabled(!disabled, egui::Button::new(glyph).min_size(ui.spacing().interact_size));
    response.widget_info(|| egui::WidgetInfo::labeled(egui::WidgetType::Button, !disabled, accessible_label));
    response.on_hover_text(accessible_label)
}

pub fn toolbar<R>(ui: &mut egui::Ui, vertical: bool, add_contents: impl FnOnce(&mut egui::Ui) -> R) -> egui::InnerResponse<R> {
    if vertical { ui.vertical(add_contents) } else { ui.horizontal(add_contents) }
}

pub fn tabs(ui: &mut egui::Ui, selected: &mut usize, labels: &[&str]) -> Vec<egui::Response> {
    let mut responses = Vec::with_capacity(labels.len());
    ui.horizontal(|ui| for (index, label) in labels.iter().enumerate() {
        let response = ui.selectable_label(*selected == index, *label);
        if response.clicked() { *selected = index; }
        responses.push(response);
    });
    responses
}

pub fn menu<R>(ui: &mut egui::Ui, label: &str, add_contents: impl FnOnce(&mut egui::Ui) -> R) -> egui::InnerResponse<Option<R>> {
    ui.menu_button(label, add_contents)
}

pub fn dialog<R>(ctx: &egui::Context, open: &mut bool, title: &str, add_contents: impl FnOnce(&mut egui::Ui) -> R) -> Option<egui::InnerResponse<Option<R>>> {
    egui::Window::new(title).open(open).collapsible(false).show(ctx, add_contents)
}

pub fn field(ui: &mut egui::Ui, label: &str, value: &mut String, error: Option<&str>) -> egui::InnerResponse<egui::Response> {
    ui.vertical(|ui| {
        ui.label(label);
        let response = ui.add(egui::TextEdit::singleline(value).hint_text(label));
        if let Some(message) = error {
            let theme = if ui.visuals().dark_mode { ThemeMode::Dark } else { ThemeMode::Light };
            ui.colored_label(Tokens::for_theme(theme, Density::Comfortable).destructive, message);
        }
        response
    })
}

pub fn checkbox(ui: &mut egui::Ui, checked: &mut bool, label: &str) -> egui::Response { ui.checkbox(checked, label) }

pub fn list_row(ui: &mut egui::Ui, selected: &mut bool, label: &str) -> egui::Response {
    let response = ui.selectable_label(*selected, label);
    if response.clicked() { *selected = !*selected; }
    response
}

pub fn split_pane<R>(ui: &mut egui::Ui, primary: impl FnOnce(&mut egui::Ui) -> R, secondary: impl FnOnce(&mut egui::Ui) -> R) {
    ui.columns(2, |columns| { primary(&mut columns[0]); secondary(&mut columns[1]); });
}

pub fn toast(ui: &mut egui::Ui, message: &str, is_error: bool) -> egui::Response {
    let tokens = Tokens::for_theme(if ui.visuals().dark_mode { ThemeMode::Dark } else { ThemeMode::Light }, Density::Comfortable);
    ui.colored_label(if is_error { tokens.destructive } else { tokens.text_primary }, message)
}

pub fn status_badge(ui: &mut egui::Ui, label: &str, is_error: bool) -> egui::Response { toast(ui, label, is_error) }

pub fn card<R>(ui: &mut egui::Ui, add_contents: impl FnOnce(&mut egui::Ui) -> R) -> egui::InnerResponse<R> {
    egui::Frame::group(ui.style()).show(ui, add_contents)
}

pub fn empty_state(ui: &mut egui::Ui, heading: &str, description: &str) -> egui::Response {
    ui.vertical_centered(|ui| { ui.heading(heading); ui.label(description) }).response
}
