// GENERATED by BrandBuilder gen_egui.py. Do not edit.
pub mod components;
pub mod tokens;

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum Density { Comfortable, Compact }

impl Density {
    pub const fn multiplier(self) -> f32 {
        match self { Self::Comfortable => tokens::COMFORTABLE_DENSITY, Self::Compact => tokens::COMPACT_DENSITY }
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum ThemeMode { Light, Dark, System }

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum PointerPrecision { None, Coarse, Fine, Mixed }

#[derive(Clone, Copy, Debug, PartialEq)]
pub struct Insets { pub top: f32, pub right: f32, pub bottom: f32, pub left: f32 }

#[derive(Clone, Debug, PartialEq)]
pub struct RuntimeCapabilities {
    pub viewport_points: egui::Vec2,
    pub safe_area: Insets,
    pub window_class: &'static str,
    pub pointer_precision: PointerPrecision,
    pub hover: bool,
    pub hardware_keyboard: bool,
    pub touch: bool,
    pub text_scale: f32,
    pub reduced_motion: bool,
    pub forced_colors: bool,
    pub ime_obstruction: Option<egui::Rect>,
    pub titlebar_regions: Vec<egui::Rect>,
    pub theme: ThemeMode,
    pub density: Density,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum CapabilityError { InvalidViewport, InvalidSafeArea, InvalidTextScale, InvalidObstruction, MissingWindowClass }

impl RuntimeCapabilities {
    pub fn validate(&self) -> Result<(), CapabilityError> {
        if !self.viewport_points.is_finite() || self.viewport_points.x <= 0.0 || self.viewport_points.y <= 0.0 {
            return Err(CapabilityError::InvalidViewport);
        }
        let insets = [self.safe_area.top, self.safe_area.right, self.safe_area.bottom, self.safe_area.left];
        if insets.iter().any(|value| !value.is_finite() || *value < 0.0) {
            return Err(CapabilityError::InvalidSafeArea);
        }
        if !self.text_scale.is_finite() || self.text_scale <= 0.0 {
            return Err(CapabilityError::InvalidTextScale);
        }
        if self.window_class.trim().is_empty() {
            return Err(CapabilityError::MissingWindowClass);
        }
        if self.ime_obstruction.iter().chain(self.titlebar_regions.iter()).any(|rect| !rect.is_finite() || !rect.is_positive()) {
            return Err(CapabilityError::InvalidObstruction);
        }
        Ok(())
    }
}
