"use client";
import { useEffect, useId, useState, type ReactNode } from "react";
import { createPortal } from "react-dom";
import { Dialog as RadixDialog, DropdownMenu, Tabs as RadixTabs, Toast as RadixToast, Toolbar as RadixToolbar } from "radix-ui";
export { AppFrameEnvironmentBridge, measureImeBlockEnd } from "./environment";

function useOverlayRoot() { const [root, setRoot] = useState<HTMLElement | null>(null); useEffect(() => { setRoot(document.getElementById("bb-overlay-root")); }, []); return root; }

export function Toolbar({ label, children, orientation = "horizontal" }: { label: string; children: ReactNode; orientation?: "horizontal" | "vertical" }) { return <RadixToolbar.Root className="bb-toolbar" aria-label={label} orientation={orientation}>{children}</RadixToolbar.Root>; }
export function ToolbarButton({ children, disabled, onClick, value, label }: { children: ReactNode; disabled?: boolean; onClick?: () => void; value?: string; label?: string }) { return <RadixToolbar.Button className="bb-control" disabled={disabled} onClick={onClick} value={value} aria-label={label}>{children}</RadixToolbar.Button>; }

export function Tabs({ label, items, defaultValue, activationMode = "automatic" }: { label: string; items: Array<{ value: string; label: string; content: ReactNode; disabled?: boolean }>; defaultValue: string; activationMode?: "automatic" | "manual" }) { return <RadixTabs.Root defaultValue={defaultValue} activationMode={activationMode}><RadixTabs.List className="bb-tabs-list" aria-label={label}>{items.map((item) => <RadixTabs.Trigger className="bb-control bb-tab" key={item.value} value={item.value} disabled={item.disabled}>{item.label}</RadixTabs.Trigger>)}</RadixTabs.List>{items.map((item) => <RadixTabs.Content key={item.value} value={item.value}>{item.content}</RadixTabs.Content>)}</RadixTabs.Root>; }

export function Menu({ label, triggerLabel, items }: { label: string; triggerLabel: string; items: Array<{ id: string; label: string; disabled?: boolean; onSelect?: () => void }> }) { const root = useOverlayRoot(); return <DropdownMenu.Root><DropdownMenu.Trigger className="bb-control" aria-label={label}>{triggerLabel}</DropdownMenu.Trigger>{root ? <DropdownMenu.Portal container={root}><DropdownMenu.Content className="bb-menu">{items.map((item) => <DropdownMenu.Item className="bb-menu-item bb-control" key={item.id} disabled={item.disabled} onSelect={item.onSelect}>{item.label}</DropdownMenu.Item>)}</DropdownMenu.Content></DropdownMenu.Portal> : null}</DropdownMenu.Root>; }

export function Dialog({ triggerLabel, title, description, children, variant = "modal" }: { triggerLabel: string; title: string; description: string; children: ReactNode; variant?: "modal" | "alert" }) { const root = useOverlayRoot(); return <RadixDialog.Root><RadixDialog.Trigger className="bb-control">{triggerLabel}</RadixDialog.Trigger>{root ? <RadixDialog.Portal container={root}><RadixDialog.Overlay /><RadixDialog.Content className="bb-dialog" role={variant === "alert" ? "alertdialog" : "dialog"}><RadixDialog.Title>{title}</RadixDialog.Title><RadixDialog.Description>{description}</RadixDialog.Description>{children}<RadixDialog.Close className="bb-control" aria-label="Close dialog">Close</RadixDialog.Close></RadixDialog.Content></RadixDialog.Portal> : null}</RadixDialog.Root>; }

export function SplitPane({ label, primary, secondary, initial = 50, orientation = "horizontal" }: { label: string; primary: ReactNode; secondary: ReactNode; initial?: number; orientation?: "horizontal" | "vertical" }) { const primaryId = useId(); const [value, setValue] = useState(Math.min(90, Math.max(10, initial))); const key = (event: React.KeyboardEvent) => { const decrement = orientation === "horizontal" ? "ArrowLeft" : "ArrowUp"; const increment = orientation === "horizontal" ? "ArrowRight" : "ArrowDown"; if (![decrement, increment, "Home", "End"].includes(event.key)) return; event.preventDefault(); if (event.key === decrement) setValue((v) => Math.max(10, v - 5)); if (event.key === increment) setValue((v) => Math.min(90, v + 5)); if (event.key === "Home") setValue(10); if (event.key === "End") setValue(90); }; const pointer = (event: React.PointerEvent<HTMLDivElement>) => { if (!event.currentTarget.hasPointerCapture(event.pointerId)) return; const bounds = event.currentTarget.parentElement?.getBoundingClientRect(); if (!bounds) return; const position = orientation === "horizontal" ? event.clientX - bounds.left : event.clientY - bounds.top; const extent = orientation === "horizontal" ? bounds.width : bounds.height; setValue(Math.min(90, Math.max(10, (position / extent) * 100))); }; const separatorOrientation = orientation === "horizontal" ? "vertical" : "horizontal"; return <div className={`bb-split-pane bb-split-pane--${orientation}`} style={{ "--bb-split": `${value}%` } as React.CSSProperties}><section id={primaryId}>{primary}</section><div className="bb-separator" role="separator" aria-controls={primaryId} aria-orientation={separatorOrientation} aria-label={label} aria-valuemin={10} aria-valuemax={90} aria-valuenow={Math.round(value)} tabIndex={0} onKeyDown={key} onPointerDown={(event) => event.currentTarget.setPointerCapture(event.pointerId)} onPointerMove={pointer} onPointerUp={(event) => event.currentTarget.releasePointerCapture(event.pointerId)} /><section>{secondary}</section></div>; }

export function Toast({ open, onOpenChange, title, description, variant = "status" }: { open: boolean; onOpenChange: (open: boolean) => void; title: string; description: string; variant?: "status" | "warning" | "error" }) { const root = useOverlayRoot(); return <RadixToast.Provider>{root ? createPortal(<><RadixToast.Root className="bb-toast" data-variant={variant} open={open} onOpenChange={onOpenChange}><RadixToast.Title>{title}</RadixToast.Title><RadixToast.Description>{description}</RadixToast.Description><RadixToast.Close className="bb-control" aria-label="Dismiss notification">Dismiss</RadixToast.Close></RadixToast.Root><RadixToast.Viewport /></>, root) : null}</RadixToast.Provider>; }
